### ISSUE TITLE
Add GPS to Luxmeter readings

### ISSUE THREAD

**Issue by scrimaglia** [philpagel/PCE174-communication#2]
Hi! Excellent code

I´m wondering if is it possible to add GPS data (lat long) to each live reading from the USB luxmeter and print it ona a CSV file.

Your coding says it´s possible to use python for reading the USB luxmeter data (specially lux measurement). I saw other people get the GPS data (from a USB dongle) and read it with python too. So, my question is if it´s possible to combine data from both USB devices in one output file, let´s say: LUX time lat long.

Many thanks in advance!

**Comment by philpagel** [comment]
Sure. If you import the code as a module and have a library to read gps coordinates from some source you can keep reading lux measurements and gps data in a loop and combine the data. E.g something along those lines:

```
import pce174 as p
import yourgpslibrary as g
import time

while True:
    dat = p.read_data("/dev/ttyUSB0", "live")
    lat, lon = g.get.coordinates()
    # print the data you are interested in
    # or do something else with it
    print(",".join([dat['date'], dat['time'], dat['value'], dat['unit'], lat, lon]))
    time.sleep(1)
```

**Comment by scrimaglia** [comment]
Ok, i´ll give it a try. I´m not a programmer at all.

Thank you very much!

**Comment by scrimaglia** [comment]
Hi, Phil. I´m stuck

Do you have a video or some tutorial to make this code work? 

Pycharm is giving me lots of errors. 

I would appreciate any kind of help from you. Thanks in advance!

**Comment by philpagel** [comment]
Well, it's hard to tell what is going wrong without seeing the code and knowing the details. Let's start with some questions:
- What gps device do you have? how is it connected?
- Which gps library are you using?
- Can you post your code?
- What error do you get?

**Comment by scrimaglia** [comment]
Sent you an email to phil@techbotch.org

**Comment by philpagel** [comment]
Resolved offline.
